# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - camel_case_types
    - prefer_generic_function_type_aliases
    - directives_ordering
    # - sort_constructors_first
    - always_put_control_body_on_new_line
    - provide_deprecation_message
    - avoid_setters_without_getters
    - avoid_void_async
    - join_return_with_assignment
    # - unnecessary_null_types
    - unnecessary_nullable_for_final_variable_declarations
    - cast_nullable_to_non_nullable
    - null_check_on_nullable_type_parameter
    - tighten_type_of_initializing_formals
    - unnecessary_null_checks

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
