name: fmatch
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  unorm_dart: ^0.1.2
#  edit_distance: ^0.4.1
  quiver: ^3.0.0-nullsafety.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
