name: fmatch
description: Fuzzy text matching engine for entity screening or person screening against denial lists such as BIS Entity List.
version: 1.3.0
homepage: https://github.com/Cat-sushi/fmatch

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  async: ^2.9.0
  html: ^0.15.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  simple_mutex: ^2.0.0
  unorm_dart: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
