name: fmatch
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-0 <3.0.0'

dependencies:
  unorm_dart: ^0.2.0
  async: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
